src/Entity/Building.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use App\Repository\BuildingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Tree\Traits\NestedSetEntity;
use Survos\CoreBundle\Entity\RouteParametersInterface;
use Survos\CoreBundle\Entity\RouteParametersTrait;
use Survos\Tree\Traits\TreeTrait;
use Survos\Tree\TreeInterface;

#[ORM\Entity(repositoryClass: BuildingRepository::class)]
#[Gedmo\Tree(type:"nested")]
class Building  implements \Stringable, RouteParametersInterface, TreeInterface
{
    use RouteParametersTrait;
    use TreeTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[ApiProperty(identifier: false)]
    private $id;
    #[ORM\ManyToOne(targetEntity: 'App\Entity\User', inversedBy: 'buildings')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;
    #[ORM\OneToMany(targetEntity: 'App\Entity\Location', mappedBy: 'building', orphanRemoval: true, cascade: ['persist'])]
    private $locations;
    #[Gedmo\Slug(fields: ['name'])]
    #[ORM\Column(type: 'string', length: 255)]
    #[ApiProperty(identifier: true)]
    private $code;
    public function __construct(#[ORM\Column(type: 'string', length: 255)] private ?string $name = null)
    {
        $this->locations = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getUser(): ?User
    {
        return $this->user;
    }
    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }
    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setBuilding($this);
        }

        return $this;
    }
    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getBuilding() === $this) {
                $location->setBuilding(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return (string)$this->getName();
    }
    public function getCode(): ?string
    {
        return $this->code;
    }
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getUniqueIdentifiers(): array
    {
        return ['buildingId' => $this->getCode()];
    }

    public function getRootLocation(): ?Location
    {
        // or filter by no parent?
        return $this->getLocations()->first() ?: null;
    }
}

src/Form/BuildingType.php
<?php

namespace App\Form;

use App\Entity\Building;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BuildingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('user')
            ->add('bulk', TextareaType::class, [
                'required' => false,
                'mapped' => false,
                'data' => "First Floor: Kitchen, Dining Room, Living Room, Bathroom\nSecond Floor: Bedroom 1, Bathroom, Bedroom 2\n",
                'help' => "Format is topName: list,of,children"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Building::class,
        ]);
    }
}

src/Controller/BuildingController.php
<?php

namespace App\Controller;

use ApiPlatform\Api\IriConverterInterface;
use ApiPlatform\Metadata\GetCollection;
use App\Entity\Building;
use App\Entity\Location;
use App\Form\BuildingType;
use App\Repository\BuildingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;

#[Route(path: '/building')]
class BuildingController extends AbstractController
{
    public function __construct(private EntityManagerInterface $entityManager) {

    }
    #[Route(path: '/browse', name: 'building_index', methods: ['GET'])]
    public function index(BuildingRepository $buildingRepository) : Response
    {
        return $this->render('building/index.html.twig', [
            'buildings' => $buildingRepository->findAll(),
        ]);
    }
    #[Route(path: '/new', name: 'building_new', methods: ['GET', 'POST'])]
    public function new(Request $request) : Response
    {
        $building = new Building();
        $form = $this->createForm(BuildingType::class, $building);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->entityManager;
            $entityManager->persist($building);
            $entityManager->flush();

            return $this->redirectToRoute('building_index');
        }
        return $this->renderForm('building/new.html.twig', [
            'building' => $building,
            'form' => $form,
        ]);
    }
    #[Route(path: '/show/{buildingId}', name: 'building_show', methods: ['GET'])]
    public function show(Building $building, EntityManagerInterface $entityManager, RouterInterface $router, IriConverterInterface $iriConverter) : Response
    {

        // debugging iriConverter with related classes
        if (false) {
            $x = $iriConverter->getIriFromResource(Location::class, operation: new GetCollection());
            assert($x == '/api/locations');

            // pass context?
            $expected = sprintf("/api/building/%s/locations", $building->getCode());
            $url = $router->generate('building_locations', ['buildingId' => $building->getCode()]); // $building->getrp());
            assert($url == $expected, $url . " should be " . $expected );

            $url = $iriConverter->getIriFromResource(Building::class, operation: (new GetCollection())->withClass(Location::class));
            assert($url == $expected, $url . " should be " . $expected );
            $url = $iriConverter->getIriFromResource(Location::class, operation: (new GetCollection())->withClass(Building::class));

        }
        $url = $iriConverter->getIriFromResource(Building::class, operation: (new GetCollection())->withClass(Location::class));



//        $operation = (new GetCollection())->withClass(Location::class);
//        // hacks...
//        $url = ($iriConverter->getIriFromResource($building, operation:$operation));
////        $url = ($iriConverter->getIriFromResource($building, operation:$operation, context: ['building_id' => $building->getId()]));
//
////        dd($url, $operation);
//
//
//        $routerProphecy = $this->prophesize(RouterInterface::class);
//
//        $routerProphecy->generate($operationName, ['id' => 1], UrlGeneratorInterface::ABS_URL)->shouldBeCalled()->willReturn('/dummies/1/foo');


        $repo = $entityManager->getRepository(Location::class);
        return $this->render('building/show.html.twig', [
            'apiUrl' => $url,
            'filter' => [
                'building' => '/api/buildings/' . $building->getId()
            ],

//            'tree' => $repo->childrenHierarchy( $repo->findOneBy(['name' => $building->getName()]), true,
//                ['html' => true, 'decorate' => true]  ),
            'building' => $building,
        ]);
    }
    #[Route(path: '/{buildingId}/edit', name: 'building_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Building $building) : Response
    {
        $form = $this->createForm(BuildingType::class, $building);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            return $this->redirectToRoute('building_index');
        }
        return $this->render('building/edit.html.twig', [
            'building' => $building,
            'form' => $form->createView(),
        ]);
    }
    #[Route(path: '/{buildingId}', name: 'building_delete', methods: ['DELETE'])]
    public function delete(Request $request, Building $building) : Response
    {
        if ($this->isCsrfTokenValid('delete'.$building->getId(), $request->request->get('_token'))) {
            $entityManager = $this->entityManager;
            $entityManager->remove($building);
            $entityManager->flush();
        }
        return $this->redirectToRoute('building_index');
    }
}

templates/building/_delete_form.html.twig
<form method="post" action="{{ path('building_delete', building.rp) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ building.id) }}">
    <button class="btn">Delete</button>
</form>

templates/building/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Building{% endblock %}

{% block body %}
    <h1>Edit Building</h1>

    {{ include('building/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('building_index') }}">back to list</a>

    {{ include('building/_delete_form.html.twig') }}
{% endblock %}

templates/building/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Building index{% endblock %}

{% block body %}


{#    {% set apiUrl = api_route(buildingClass) %}#}
{#    <div id="location_manager"#}
{#         class="demo"#}
{#         data-api-base="{{ apiUrl }}"#}
{#    >#}
{#        <h3>All Buildings:</h3>#}
{#        <div id="all_locations" class="demo"></div>#}
{#        <hr />#}

{#    </div>#}


    <h1>Building index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>#Locations</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for building in buildings %}
            <tr>
                <td>{{ building.id }}</td>
                <td>{{ building.name }}</td>
                <td>{{ building.locations.count }}</td>
                <td>
                    <a href="{{ path('building_show', building.rp) }}">show</a>
                    <a href="{{ path('building_edit', building.rp) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('building_new') }}">Create new</a>
{% endblock %}

templates/building/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Building{% endblock %}

{% block body %}
    <h1>Create new Building</h1>

    {{ include('building/_form.html.twig') }}

    <a href="{{ path('building_index') }}">back to list</a>
{% endblock %}

templates/building/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Building: {{ building.name }} ({{ building.locations.count }} children){% endblock %}

{% set html_tree %}
    {% tree item in building.rootLocation.children %}
        {{ treeloop.first ? '<ul>' }}
        <li class="jstree-open">
            #{{ treeloop.index }}
            {{ item.name }}
            {#        <a href="{{ path('build') }}">{{ item.name }}</a>#}
            {% subtree item.children %}
        </li>
        {{ treeloop.last ? '</ul>' }}
    {% endtree %}
{% endset %}

{% block body %}
<h1>{{ block('title') }}</h1>

{#    {{ dump(building) }}#}
{#    {{ dump(building.rootLocation) }}#}
{#    {{ dump(building.rootLocation.children|length) }}#}

    <h3>Tree Data</h3>
    {{ html_tree|escape }}
    {{ html_tree }}

    <h3>api_tree Component with {{  apiUrl }}</h3>
    {% component api_tree with {
        apiUrl: apiUrl,
        caller: 'caller?',
        class: 'App\\Entity\\Location',
    } %}
    {% endcomponent %}

    {% endblock %}

{% block playground %}
    <h3>Tree Component (HTML)</h3>
    {% component tree %}
        {% block data %}
            Data here.
            {{ html_tree }}
        {% endblock  %}
    {% endcomponent %}

{% set _controller = '@survos/tree-bundle/api_tree' %}
{#{% set apiUrl = path('api_locations_get_collection') %}#}
<h3>AJAX Tree, using {{ _controller }} and {{ apiUrl }}</h3>
<div
{{ stimulus_controller(_controller, {
    apiCall: apiUrl,
    filter: filter
}) }}
>
    <div {{ stimulus_target(_controller, 'message') }}>Messages go here.</div>

    <ol {{ stimulus_target(_controller, 'ajax') }}>
        Ajax tree will be populated here.
    </ol>
</div>



{#{% set _controller = '@survos/tree-bundle/tree' %}#}
{% set _controller = 'jstree' %}
    {% if true %}
<h3>HTML Tree, using stimulus {{ _controller }}</h3>
<div
        {{ stimulus_controller(_controller) }}
        {{ stimulus_target(_controller, 'html')
        }}>

{% tree item in [building.rootLocation] %}
    {% if treeloop.first %}<ul >{% endif %}
    <li class="jstree-open">
        #{{ treeloop.index }}
        {{ item.name }}
{#        <a href="{{ path('build') }}">{{ item.name }}</a>#}
        {% subtree item.children %}
    </li>
    {% if treeloop.last %}</ul>{% endif %}
{% endtree %}
</div>
    {% endif %}

{#<h3>Using locationManagerApp for building {{ building.id }}/{{ apiUrl }}</h3>#}
{#<div id="location_manager"#}
{#     class="demo"#}
{#     data-building-id="{{ building.id }}"#}
{#     data-api-base="{{ apiUrl }}"#}
{#>#}
{#    <h3>Specific Building: {{ building.id }} {{ building }}</h3>#}
{#    <div id="building_locations"#}
{#         data-building-id="{{ building.id }}" class="demo"></div>#}
{#</div>#}


<table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ building.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ building.name }}</td>
            </tr>
        </tbody>
    </table>

    <h3>
        {{ building.name }} Locations:
    </h3>


    {% for location in building.locations %}
        <li>
            {{ location.parent ? location.parent.name }} /
            {{ location.name }}
        </li>
    {% endfor %}

    <a href="{{ path('building_edit', building.rp) }}">edit</a>

    {{ include('building/_delete_form.html.twig') }}
{% endblock %}